services:
  - type: web
    name: marketplace-backend
    env: docker
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: FRONTEND_URL
        fromService:
          type: web
          name: marketplace-frontend
          property: host
  - type: web
    name: marketplace-frontend
    env: static
    branch: main
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: marketplace-backend
          property: host
