# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# Variables
@scheme = http
@host = localhost
@PORT = {{$dotenv PORT}} 
@baseUrl = {{scheme}}://{{host}}:{{PORT}}

# Dynamic Variables
@authToken = {{login.response.body.token}}
@authToken = {{signup.response.body.token}}

@userId = {{login.response.body.id}}
@userId = {{signup.response.body.id}}

### health check

GET {{baseUrl}}/health

### Signup - password length too short

# @name signup
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
    "name": "test",
    "email": "example@example.com",
    "password": "test123"
}

### successful signup

# @name signup
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
    "name": "test",
    "email": "example@example.com",
    "password": "CorrectHorseBatteryStaple"
}

### successful login

# @name login
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "CorrectHorseBatteryStaple"
}

### unsuccessful login - wrong password

# @name login
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "WrongPassword"
}

### unsuccessful login - wrong email

# @name login
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
    "email": "foo@example.com",
    "password": "WrongPassword"
}

### get all users - unauthorized - no Authorization header

GET {{baseUrl}}/api/v1/users

### get all users - authorized

GET {{baseUrl}}/api/v1/users
Authorization: Bearer {{authToken}}

### get all users - unauthorized - malformed token

GET {{baseUrl}}/api/v1/users
Authorization: Bearer malformedToken

### get all users - unauthorized - no token

GET {{baseUrl}}/api/v1/users
Authorization: Bearer 

### get all users - unauthorized - expired token

GET {{baseUrl}}/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJjMzE2MjExLWM5ZjQtNDM3Yy04MDQyLTllNWRjMGVlMWQxZSIsImVtYWlsIjoiZXhhbXBsZTJAZXhhbXBsZS5jb20iLCJpYXQiOjE2ODA1NDM1OTEsImV4cCI6MTY4MDU0NzE5MX0.ch7iKLKNluWKg_84dG9YALsA2RHpA7KGwfwyaXVeyhQ

### get user by id

GET {{baseUrl}}/api/v1/users/{{userId}}
Authorization: Bearer {{authToken}}

### get user by id - not found

GET {{baseUrl}}/api/v1/users/thisIsNotAnExistingUserId
Authorization: Bearer {{authToken}}
