version: "3"
services:
  db:
    image: mysql:8
    # image: mariadb:10
    volumes:
      - "./init-scripts/dev:/docker-entrypoint-initdb.d"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
      TZ: UTC
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: "mysql -u root -ppassword -e 'SELECT 1'"
      interval: 30s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
