name: Frontend
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/frontend.yml
  workflow_dispatch:
jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Run prettier style check
        working-directory: ./frontend
        run: npx prettier --check .
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install node-modules
        working-directory: ./frontend
        run: npm ci
      - name: Run eslint
        working-directory: ./frontend
        run: npx eslint . --ext ".js,.jsx"
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install node-modules
        working-directory: ./frontend
        run: npm ci
      - name: Run tests
        working-directory: ./frontend
        run: npx vitest run --coverage
      - name: Save coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./frontend/coverage
  e2e-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Start MySQL server
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: 8.0
          auto-start: true
      - name: Setup MySQL server
        run: |
          mysql -u root -h 127.0.0.1 <<< "CREATE DATABASE test; ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'; FLUSH PRIVILEGES;"
      - name: Seed Database
        working-directory: ./db/init-scripts/dev
        run: mysql -h 127.0.0.1 -P 3306 -u root -ppassword test < init_test.sql
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install frontend node-modules
        working-directory: ./frontend
        run: npm ci
      - name: Install backend node-modules
        working-directory: ./backend
        run: npm ci
      - name: Start backend
        working-directory: ./backend
        run: npm run dev &
      - name: Start frontend
        working-directory: ./frontend
        run: npm run dev &
      - name: Run e2e tests
        working-directory: ./frontend
        run: npm run test:e2e
      - name: Save e2e test videos
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-videos
          path: ./frontend/cypress/videos
  deploy:
    env:
      FRONTEND_DEPLOY_WEBHOOK: ${{secrets.FRONTEND_DEPLOY_WEBHOOK}}
    needs: [prettier-check, lint, tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - if: env.FRONTEND_DEPLOY_WEBHOOK != ''
        name: Trigger deploy to production
        run: curl ${{secrets.FRONTEND_DEPLOY_WEBHOOK}}
