name: Frontend PR
on:
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/frontend-pr.yml
  workflow_dispatch:
jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Run prettier style check
        working-directory: ./frontend
        run: npx prettier --check .
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install node-modules
        working-directory: ./frontend
        run: npm ci
      - name: Run eslint
        working-directory: ./frontend
        run: npx eslint . --ext ".js,.jsx"
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v3
      - name: Install node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install node-modules
        working-directory: ./frontend
        run: npm ci
      - name: Run tests
        working-directory: ./frontend
        run: npm run test:run
